name: Recent Commits

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      
      - name: Update Recent Commits
        uses: umutphp/github-action-dynamic-profile-page@v0.6.0
        with:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          COMMIT_MESSAGE: "Update recent activity"
          COMMIT_NAME: "FrancisLucanoLeonelGuzman"
          COMMIT_EMAIL: "FrancisLucanoLeonelGuzman@hotmail.com"

