name: Recent Commits

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update Recent Commits
        uses: umutphp/github-action-dynamic-profile-page@v5
        with:
          github-username: 'FrancisLucanoLeonelGuzman'
          user-email: 'FrancisLucanoLeonelGuzman@hotmail.com'
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}

